// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/observatory/multiobservatory/config.proto

package multiobservatory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ObserverConfig defines one observatory group with a dedicated balancer tag.
type ObserverConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Tag      string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	ProbeUrl string                 `protobuf:"bytes,2,opt,name=probe_url,json=probeUrl,proto3" json:"probe_url,omitempty"`
	// Durations use nanoseconds, matching time.Duration and HealthPingConfig.
	ProbeInterval   int64    `protobuf:"varint,3,opt,name=probe_interval,json=probeInterval,proto3" json:"probe_interval,omitempty"`
	SubjectSelector []string `protobuf:"bytes,4,rep,name=subject_selector,json=subjectSelector,proto3" json:"subject_selector,omitempty"`
	Timeout         int64    `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	HttpMethod      string   `protobuf:"bytes,6,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	SamplingCount   int32    `protobuf:"varint,7,opt,name=sampling_count,json=samplingCount,proto3" json:"sampling_count,omitempty"`
	Connectivity    string   `protobuf:"bytes,8,opt,name=connectivity,proto3" json:"connectivity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ObserverConfig) Reset() {
	*x = ObserverConfig{}
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserverConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverConfig) ProtoMessage() {}

func (x *ObserverConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverConfig.ProtoReflect.Descriptor instead.
func (*ObserverConfig) Descriptor() ([]byte, []int) {
	return file_app_observatory_multiobservatory_config_proto_rawDescGZIP(), []int{0}
}

func (x *ObserverConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ObserverConfig) GetProbeUrl() string {
	if x != nil {
		return x.ProbeUrl
	}
	return ""
}

func (x *ObserverConfig) GetProbeInterval() int64 {
	if x != nil {
		return x.ProbeInterval
	}
	return 0
}

func (x *ObserverConfig) GetSubjectSelector() []string {
	if x != nil {
		return x.SubjectSelector
	}
	return nil
}

func (x *ObserverConfig) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ObserverConfig) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *ObserverConfig) GetSamplingCount() int32 {
	if x != nil {
		return x.SamplingCount
	}
	return 0
}

func (x *ObserverConfig) GetConnectivity() string {
	if x != nil {
		return x.Connectivity
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observers     []*ObserverConfig      `protobuf:"bytes,1,rep,name=observers,proto3" json:"observers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_observatory_multiobservatory_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetObservers() []*ObserverConfig {
	if x != nil {
		return x.Observers
	}
	return nil
}

var File_app_observatory_multiobservatory_config_proto protoreflect.FileDescriptor

const file_app_observatory_multiobservatory_config_proto_rawDesc = "" +
	"\n" +
	"-app/observatory/multiobservatory/config.proto\x12*xray.core.app.observatory.multiobservatory\"\x97\x02\n" +
	"\x0eObserverConfig\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1b\n" +
	"\tprobe_url\x18\x02 \x01(\tR\bprobeUrl\x12%\n" +
	"\x0eprobe_interval\x18\x03 \x01(\x03R\rprobeInterval\x12)\n" +
	"\x10subject_selector\x18\x04 \x03(\tR\x0fsubjectSelector\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x03R\atimeout\x12\x1f\n" +
	"\vhttp_method\x18\x06 \x01(\tR\n" +
	"httpMethod\x12%\n" +
	"\x0esampling_count\x18\a \x01(\x05R\rsamplingCount\x12\"\n" +
	"\fconnectivity\x18\b \x01(\tR\fconnectivity\"b\n" +
	"\x06Config\x12X\n" +
	"\tobservers\x18\x01 \x03(\v2:.xray.core.app.observatory.multiobservatory.ObserverConfigR\tobserversBEZCgithub.com/v2rayA/v2raya-core/hint/app/observatory/multiobservatoryb\x06proto3"

var (
	file_app_observatory_multiobservatory_config_proto_rawDescOnce sync.Once
	file_app_observatory_multiobservatory_config_proto_rawDescData []byte
)

func file_app_observatory_multiobservatory_config_proto_rawDescGZIP() []byte {
	file_app_observatory_multiobservatory_config_proto_rawDescOnce.Do(func() {
		file_app_observatory_multiobservatory_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_observatory_multiobservatory_config_proto_rawDesc), len(file_app_observatory_multiobservatory_config_proto_rawDesc)))
	})
	return file_app_observatory_multiobservatory_config_proto_rawDescData
}

var file_app_observatory_multiobservatory_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_observatory_multiobservatory_config_proto_goTypes = []any{
	(*ObserverConfig)(nil), // 0: xray.core.app.observatory.multiobservatory.ObserverConfig
	(*Config)(nil),         // 1: xray.core.app.observatory.multiobservatory.Config
}
var file_app_observatory_multiobservatory_config_proto_depIdxs = []int32{
	0, // 0: xray.core.app.observatory.multiobservatory.Config.observers:type_name -> xray.core.app.observatory.multiobservatory.ObserverConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_observatory_multiobservatory_config_proto_init() }
func file_app_observatory_multiobservatory_config_proto_init() {
	if File_app_observatory_multiobservatory_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_observatory_multiobservatory_config_proto_rawDesc), len(file_app_observatory_multiobservatory_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_observatory_multiobservatory_config_proto_goTypes,
		DependencyIndexes: file_app_observatory_multiobservatory_config_proto_depIdxs,
		MessageInfos:      file_app_observatory_multiobservatory_config_proto_msgTypes,
	}.Build()
	File_app_observatory_multiobservatory_config_proto = out.File
	file_app_observatory_multiobservatory_config_proto_goTypes = nil
	file_app_observatory_multiobservatory_config_proto_depIdxs = nil
}
